/**
* OOPSBannerApp UC4 – Banner Display Application using .join() method and loops
*
* This class demonstrates the creation of a visual banner displaying the word "OOPS"
* using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
* console using individual print statements for each line, creating a decorativ
* text effect. The String method .join() and loops are used to accomplish this.
*
* The banner is generated by printing predefined string patterns line by line
* where each line contributes to forming the letters O, O, P, and S in a stylized format.
* This extends a basic user story by adding visual presentation to a simple message output.
*
* @author Developer
* @version 4
*/

public class OOPSLoopBanner {
    public static void main(String[] args) {
		String str[] = new String[7];
		str[0] = String.join(" "," *****  ","  *****  "," *****  ","  ***** ");
        str[1] = String.join(" ","*     * "," *     * "," *    * ","  *     ");
        str[2] = String.join(" ","*     * "," *     * "," *    * ","  *     ");
        str[3] = String.join(" ","*     * "," *     * "," *****  ","  ***** ");
        str[4] = String.join(" ","*     * "," *     * "," *      ","      * ");
        str[5] = String.join(" ","*     * "," *     * "," *      ","      * ");
		str[6] = String.join(" "," *****  ","  *****  "," *      ","  ***** ");
		
		for (String s:str) {
			System.out.println(s);
		}
    }
}