/**
* OOPSBannerApp UC7 – Banner Display Application
*
* This class demonstrates the creation of a visual banner displaying the word "OOPS"
* using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
* console using individual print statements for each line, creating a decorativ
* text effect.
*
* We are using inner classes to accomplish this
*
* The banner is generated by printing predefined string patterns line by line
* where each line contributes to forming the letters O, O, P, and S in a stylized format.
* This extends a basic user story by adding visual presentation to a simple message output.
*
* @author Developer
* @version 7
*/

public class OOPSBannerApp {
    static class CharPattern {
        char ch;
        String[] pat;
        CharPattern(char ch, String[] pat) {
            this.ch = ch;
            this.pat = pat;
        }
    }

    public static CharPattern[] createCharPatternMaps() {
        return new CharPattern[] {
            new CharPattern('O', new String[] {
                " **** ",
                "*    *",
                "*    *",
                "*    *",
                "*    *",
                "*    *",
                " **** "
            }),
            new CharPattern('P', new String[] {
                " **** ",
                "*    *",
                "*    *",
                "***** ",
                "*     ",
                "*     ",
                "*     "
            }),
            new CharPattern('S', new String[] {
                " **** ",
                "*     ",
                "*     ",
                " **** ",
                "     *",
                "     *",
                " **** "
            })
        };
    }

    public static String[] getCharPattern(char ch, CharPattern[] charMaps) {
        for (CharPattern m:charMaps) {
            if (m.ch == ch)
                return m.pat;
        }
        return new String[] {" "}; 
    }

    public static void printMyText(String text, CharPattern[] charMaps) {
        for (int row = 0; row < 7; row++) {
            for (int i = 0; i < text.length(); i++) {
                String[] pat = getCharPattern(text.charAt(i), charMaps);
                System.out.print(pat[row]+" ");
            }
            System.out.println();
        }
    }

    public static void main(String[] args) {
        CharPattern[] charMaps = createCharPatternMaps();
        String text = "OOPS";
        printMyText(text, charMaps);
    }
}